    version: 2
    jobs:
        build:
            docker:
                - image: circleci/java
            steps:
                - checkout
                - restore_cache:
                    keys:
                        - build-tools-{{ .Environment.CACHE_VERSION }}
                - run:
                    name: Setup
                    command: bash bin/install-build-tools.sh
                - run:
                    name: Static Analysis
                    command: build_tools/pmd/bin/run.sh pmd -d src/ \
                        -R rulesets/apex-basic.xml -f text \
                        -r static-analysis.txt
                - run:
                    name: Authorize
                    command: build_tools/force login -i $SFDC_HOST -u $SFDC_USERNAME -p "$SFDC_PASSWORD$SFDC_SECURITY_TOKEN"
                - run:
                    name: Test
                    command: build_tools/force import -v -c -test -d src
                - save_cache:
                    key: build-tools-{{ .Environment.CACHE_VERSION }}
                    paths:
                        - build_tools
                - store_artifacts:
                    path: static-analysis.txt
