    version: 2
    jobs:
        build:
            docker:
                - image: debian:stretch
            steps:
                - checkout
                - restore_cache:
                    keys: build-tools
                - run:
                    name: Install build tools
                    command: bash ./bin/install-build-tools.sh
                - run:
                    name: Login to test org
                    command: build_tools/force login -i $SFDC_HOST -u $SFDC_USERNAME -p "$SFDC_PASSWORD$SFDC_SECURITY_TOKEN"
                - run:
                    name: Run tests
                    command: build_tools/force import -c -l RunLocalTests -d src
                - save_cache:
                    key: build-tools
                    paths:
                        - build_tools
